name: Deploy to EC2 from Latest GitHub Release

on:
  release:
    types: [published]  # 릴리스가 게시될 때 트리거
  workflow_dispatch:    # 수동 실행을 허용하는 이벤트

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      # 1. 최신 릴리스에서 파일 목록을 확인하고 첫 번째 자산을 다운로드
      - name: Get Latest Release Asset
        id: get_asset
        run: |
          latest_release=$(curl -s https://api.github.com/repos/reposy/springboot-kotlin/releases/latest)
          asset_url=$(echo $latest_release | jq -r '.assets[0].browser_download_url')
          asset_name=$(echo $latest_release | jq -r '.assets[0].name')
          echo "Latest asset URL: $asset_url"
          echo "Latest asset name: $asset_name"
          curl -L -o $asset_name $asset_url
          echo "asset_name=$asset_name" >> $GITHUB_ENV
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV  # 리포지토리 이름을 환경 변수에 저장
          echo "IMAGE_NAME=${{ env.REPO_NAME }}-image" >> $GITHUB_ENV  # 이미지 이름을 환경 변수에 저장
          echo "CONTAINER_NAME=${{ env.REPO_NAME }}-container" >> $GITHUB_ENV  # 컨테이너 이름을 환경 변수에 저장

      # 2. JAR 파일을 EC2로 업로드
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ${{ env.asset_name }}  # 자동으로 가져온 파일 이름
          target: /home/ubuntu/sypg/${{ env.REPO_NAME }}/app.jar  # EC2의 지정된 경로에 저장

      # 3. EC2에서 Git pull 및 Docker 이미지 빌드 및 실행
      - name: Pull latest code and Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/sypg/springboot-kotlin  # 리포지토리 경로로 이동
            git pull origin master                  # 최신 코드 가져오기
            sudo docker build -t ${{ env.IMAGE_NAME }} .  # Docker 이미지 빌드
            sudo docker stop ${{ env.CONTAINER_NAME }} || true  # 기존 컨테이너 중지
            sudo docker rm ${{ env.CONTAINER_NAME }} || true    # 기존 컨테이너 제거
            sudo docker run -d -p 8080:8080 --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}