name: Deploy to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 트리거
  workflow_dispatch:   # 수동 실행을 허용하는 이벤트

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub에서 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. EC2 인스턴스에 SSH로 접속하여 작업 실행
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/sypg/springboot-kotlin   # 프로젝트 디렉터리로 이동
            git pull origin master                     # 최신 코드 가져오기
            ./gradlew build                          # 프로젝트 빌드
            docker build -t springboot-kotlin .      # Docker 이미지 빌드
            docker stop springboot-app || true       # 기존 컨테이너 중지
            docker rm springboot-app || true         # 기존 컨테이너 제거
            docker run -d -p 8080:8080 --name springboot-app springboot-kotlin  # 컨테이너 실행